import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import confetti from 'canvas-confetti';
import { ArrowDown, CakeSlice, Check, Gift, Music, Music2, PartyPopper, RotateCcw, Send, Sparkles, Volume2, VolumeX } from 'lucide-react';
import './styles.css';

// All editable birthday content lives here. Replace `photo` and `music` with the real assets when ready.
const BIRTHDAY_CONFIG = {
  name: 'Abhinav Pandey',
  // Local birthday photos. Replace these paths only if the assets are moved.
  photos: ['/asset/img1.jpeg', '/asset/img2.jpeg', '/asset/img3.jpeg', '/asset/img4.jpeg', '/asset/img5.jpeg'],
  backgroundImage: '/birthday-background.png',
  // Replace with a local file or URL, e.g. '/audio/birthday-song.mp3'. Music starts only after Tap to Open.
  music: '', sender: 'Didi & Jiju',
  revealMessage: 'Wishing you lots of happiness, success and wonderful moments. May you always keep smiling and get everything you wish for.',
  profile: { role: 'Best Brother & Saale Sahab', attitude: 'Unlimited 😎', happiness: 'Always Active', age: 'Classified 🔒', maturity: 'Loading...', newVersion: 'Successfully Installed ✅' }
};

const fire = (count = 110) => confetti({ particleCount: count, spread: 75, startVelocity: 30, origin: { y: .68 }, colors: ['#f8d47a', '#d7a94b', '#ffffff', '#8db7cc'] });

function Background() { return <div className="background" aria-hidden="true"><img src={BIRTHDAY_CONFIG.backgroundImage} alt="" style={{ position: 'absolute', inset: '-16px', width: 'calc(100% + 32px)', height: 'calc(100% + 32px)', objectFit: 'cover', filter: 'blur(2px) saturate(1.15)', opacity: .68 }}/><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, #07111f90 0%, #07111f70 48%, #040a12b8 100%)' }}/><div className="orb orb-one"/><div className="orb orb-two"/><div className="stars">{Array.from({ length: 36 }, (_, i) => <i key={i} style={{ '--i': i }} />)}</div></div>; }

function MusicButton({ audio, playing, setPlaying }) {
  const toggle = () => { if (!audio.current) return; if (playing) audio.current.pause(); else audio.current.play().catch(() => {}); setPlaying(!playing); };
  return <button className="music-button" onClick={toggle} aria-label={playing ? 'Turn music off' : 'Turn music on'}>{playing ? <Volume2 size={18}/> : <VolumeX size={18}/>} <span>{playing ? 'Music on' : 'Music off'}</span></button>;
}

function GiftScreen({ onOpen }) { return <motion.main className="opening" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="eyebrow"><Sparkles size={15}/> A little something for you</div><h1>A Special Surprise<br/><em>for Abhinav</em> <span>🎁</span></h1><p className="intro">A tiny cinematic celebration for someone truly one of a kind.</p><motion.div className="gift" animate={{ y: [0, -9, 0], rotate: [0, -1, 1, 0] }} transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}><div className="gift-lid"/><div className="gift-box"><span className="ribbon-v"/><span className="ribbon-h"/></div><div className="gift-glow"/></motion.div><button className="primary-button" onClick={onOpen}><Gift size={18}/> Tap to Open <ArrowDown size={17}/></button><div className="scroll-hint">Your surprise awaits <span>↓</span></div></motion.main>; }

function Balloons() { return <div className="balloons" aria-hidden="true"><span className="balloon b1"/><span className="balloon b2"/><span className="balloon b3"/><span className="balloon b4"/></div>; }

function Reveal({ onProfile }) { const [selectedPhoto, setSelectedPhoto] = useState(0); return <section className="reveal section" id="birthday"><Balloons/><div className="section-kicker">THE DAY IS YOURS</div><motion.div className="portrait-wrap" initial={{ scale: .75, opacity: 0 }} whileInView={{ scale: 1, opacity: 1 }} viewport={{ once: true }}><div className="portrait-ring"><AnimatePresence mode="wait"><motion.img key={selectedPhoto} src={BIRTHDAY_CONFIG.photos[selectedPhoto]} alt={`Photo ${selectedPhoto + 1} of Abhinav Pandey`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}/></AnimatePresence><span className="portrait-dot"/></div></motion.div><div className="photo-gallery" aria-label="Abhinav photo gallery">{BIRTHDAY_CONFIG.photos.map((photo, index) => <button key={photo} className={`photo-thumb ${index === selectedPhoto ? 'active' : ''}`} onClick={() => setSelectedPhoto(index)} aria-label={`Show photo ${index + 1}`}><img src={photo} alt=""/></button>)}</div><motion.h2 initial={{ y: 20, opacity: 0 }} whileInView={{ y: 0, opacity: 1 }} viewport={{ once: true }}>Happy Birthday<br/><strong>{BIRTHDAY_CONFIG.name} <span>🎂</span></strong></motion.h2><p className="message">{BIRTHDAY_CONFIG.revealMessage}</p><button className="outline-button" onClick={onProfile}>Check Birthday Profile <span>😎</span></button></section>; }

function Profile({ onSurprise }) { const [loaded, setLoaded] = useState(false); useEffect(() => { const t = setTimeout(() => setLoaded(true), 2200); return () => clearTimeout(t); }, []); return <section className="section profile-section" id="profile"><div className="section-kicker">A QUICK SYSTEM SCAN</div><motion.div className="terminal glass" initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="terminal-top"><span className="traffic red"/><span className="traffic yellow"/><span className="traffic green"/><small>abhinav@birthday ~ profile.js</small></div><div className="code"><span className="pink">const</span> <span className="blue">abhinavPandey</span> = {'{'}<br/>{Object.entries(BIRTHDAY_CONFIG.profile).map(([key, value]) => <div className="code-line" key={key}><span className="blue">&nbsp;&nbsp;{key}</span>: <span className="gold">&quot;{value}&quot;</span>,</div>)}{'}'};</div><div className="loading-label"><span>Checking Abhinav’s maturity...</span><span>{loaded ? '100%' : '78%'}</span></div><div className="loading-track"><motion.div className="loading-fill" animate={{ width: loaded ? '100%' : '78%' }} transition={{ duration: 2.2 }}/></div><AnimatePresence>{loaded && <motion.div className="terminal-result" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><Check size={16}/> Maturity not found, but awesomeness is unlimited! 😂</motion.div>}</AnimatePresence></motion.div><button className="primary-button" onClick={onSurprise}>Reveal Your Surprise <Sparkles size={17}/></button></section>; }

function ScratchCard({ onDone }) { const canvasRef = useRef(null); const [scratched, setScratched] = useState(false); const drawing = useRef(false); useEffect(() => { const c = canvasRef.current, ctx = c.getContext('2d'); ctx.fillStyle = '#c89a42'; ctx.fillRect(0, 0, c.width, c.height); ctx.fillStyle = '#f4d27b'; ctx.font = '600 18px Inter, sans-serif'; ctx.textAlign = 'center'; ctx.fillText('SCRATCH HERE', c.width / 2, c.height / 2 + 6); }, []); const scratch = e => { if (scratched) return; const c = canvasRef.current, r = c.getBoundingClientRect(), point = e.touches ? e.touches[0] : e; const x = (point.clientX - r.left) * c.width / r.width, y = (point.clientY - r.top) * c.height / r.height; const ctx = c.getContext('2d'); ctx.globalCompositeOperation = 'destination-out'; ctx.beginPath(); ctx.arc(x, y, 28, 0, Math.PI * 2); ctx.fill(); }; const end = () => { drawing.current = false; const data = canvasRef.current.getContext('2d').getImageData(0, 0, canvasRef.current.width, canvasRef.current.height).data; let clear = 0; for (let i = 3; i < data.length; i += 16) if (data[i] < 80) clear++; if (clear > data.length / 64) { setScratched(true); onDone?.(); fire(55); } }; return <section className="section scratch-section" id="surprise"><div className="section-kicker">A LITTLE REWARD</div><h2>Abhinav, scratch to reveal<br/><em>your birthday reward!</em></h2><div className="scratch-card"><div className="reward">🎁 <strong>Unlimited happiness + one party pending from the Birthday Boy! 😂</strong></div><canvas ref={canvasRef} width="560" height="190" onMouseDown={() => drawing.current = true} onMouseMove={e => drawing.current && scratch(e)} onMouseUp={end} onMouseLeave={end} onTouchStart={() => drawing.current = true} onTouchMove={e => { e.preventDefault(); drawing.current && scratch(e); }} onTouchEnd={end} className={scratched ? 'scratched' : ''} aria-label="Interactive scratch card"/></div><p className="tiny-note">Use your finger or mouse to scratch</p></section>; }

function Cake({ onCut }) { const [cut, setCut] = useState(false); const cutCake = () => { setCut(true); fire(150); onCut?.(); }; return <section className="section cake-section" id="cake"><div className="section-kicker">THE GRAND FINALE</div><h2>Make a wish and<br/><em>cut the cake! 🎂</em></h2><div className={`cake ${cut ? 'cut' : ''}`}><div className="candles"><span/><span/><span/></div><div className="flames">{!cut && <><i/><i/><i/></>}</div><div className="cake-top"/><div className="cake-body"><span/><span/><span/></div><div className="plate"/></div><AnimatePresence mode="wait">{cut ? <motion.div className="cake-success" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>Cake successfully cut! Ab party kab de rahe ho? 😄</motion.div> : <button className="primary-button" onClick={cutCake}><CakeSlice size={18}/> Cut the Cake</button>}</AnimatePresence></section>; }

function FinalMessage({ onReplay }) { const share = () => { const text = encodeURIComponent('Happy Birthday Abhinav Pandey! 🎂 Wishing you unlimited happiness and success. Open your surprise:'); window.open(`https://wa.me/?text=${text}%20${encodeURIComponent(window.location.href)}`, '_blank', 'noopener,noreferrer'); }; return <section className="section final-section"><motion.div className="final-card glass" initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="seal"><PartyPopper size={19}/></div><div className="section-kicker">A NOTE FROM THE HEART</div><h2>Dear Abhinav,</h2><p>Aap hamesha khush rahen, muskurate rahen aur life mein bahut success paayen. Aapko jo bhi chahiye, woh sab mile.</p><p>Happy Birthday once again! <span>❤️</span></p><div className="signature">With love,<br/><strong>{BIRTHDAY_CONFIG.sender}</strong></div></motion.div><pre className="code-ending">while (life) {'{'}<br/>&nbsp; keepSmiling();<br/>&nbsp; stayAwesome();<br/>&nbsp; achieveYourDreams();<br/>{'}'}<br/><span>// Happy Birthday Abhinav! 🎉</span></pre><div className="final-actions"><button className="outline-button" onClick={share}><Send size={17}/> Share on WhatsApp</button><button className="text-button" onClick={onReplay}><RotateCcw size={16}/> Replay surprise</button></div><footer>Made with a little extra sparkle for Abhinav · 2024</footer></section>; }

function App() { const [opened, setOpened] = useState(false), [playing, setPlaying] = useState(false), audio = useRef(null); const reduced = useReducedMotion(); const open = () => { setOpened(true); fire(130); if (audio.current) { audio.current.play().then(() => setPlaying(true)).catch(() => {}); } setTimeout(() => document.getElementById('birthday')?.scrollIntoView({ behavior: reduced ? 'auto' : 'smooth' }), 250); }; const replay = () => { setOpened(false); setPlaying(false); window.scrollTo({ top: 0, behavior: reduced ? 'auto' : 'smooth' }); }; return <div className="app"><Background/><audio ref={audio} loop src={BIRTHDAY_CONFIG.music} />{opened && <MusicButton audio={audio} playing={playing} setPlaying={setPlaying}/>}<AnimatePresence mode="wait">{!opened ? <GiftScreen key="gift" onOpen={open}/> : <motion.div key="content" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Reveal onProfile={() => document.getElementById('profile')?.scrollIntoView({ behavior: 'smooth' })}/><Profile onSurprise={() => document.getElementById('surprise')?.scrollIntoView({ behavior: 'smooth' })}/><ScratchCard onDone={() => {}}/><Cake/><FinalMessage onReplay={replay}/></motion.div>}</AnimatePresence></div>; }

createRoot(document.getElementById('root')).render(<App />);
